//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlagsRally.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlagsRally.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the selected folder denied..
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone..
        /// </summary>
        internal static string ActionCannotUndone {
            get {
                return ResourceManager.GetString("ActionCannotUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Area.
        /// </summary>
        internal static string AdminArea {
            get {
                return ResourceManager.GetString("AdminArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Countries.
        /// </summary>
        internal static string AllCountries {
            get {
                return ResourceManager.GetString("AllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pins.
        /// </summary>
        internal static string AllPins {
            get {
                return ResourceManager.GetString("AllPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the backup file?.
        /// </summary>
        internal static string AreYouSureRestoreBackup {
            get {
                return ResourceManager.GetString("AreYouSureRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival location.
        /// </summary>
        internal static string ArrivalLocation {
            get {
                return ResourceManager.GetString("ArrivalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Location Info..
        /// </summary>
        internal static string ArrivalLocationInfo {
            get {
                return ResourceManager.GetString("ArrivalLocationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder in the Download folder..
        /// </summary>
        internal static string BackupInstruction {
            get {
                return ResourceManager.GetString("BackupInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup saved successfully!.
        /// </summary>
        internal static string BackupSucceeded {
            get {
                return ResourceManager.GetString("BackupSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Visas.
        /// </summary>
        internal static string BannerVisas {
            get {
                return ResourceManager.GetString("BannerVisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        internal static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is cleared successfully!.
        /// </summary>
        internal static string ClearAPIKey {
            get {
                return ResourceManager.GetString("ClearAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm the current location and tap &apos;Get Location&apos; below..
        /// </summary>
        internal static string ConfirmLocationTapButton {
            get {
                return ResourceManager.GetString("ConfirmLocationTapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reset?.
        /// </summary>
        internal static string ConfirmReset {
            get {
                return ResourceManager.GetString("ConfirmReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Residence.
        /// </summary>
        internal static string CountryOfResidence {
            get {
                return ResourceManager.GetString("CountryOfResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create backup.
        /// </summary>
        internal static string CreateBackup {
            get {
                return ResourceManager.GetString("CreateBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Board.
        /// </summary>
        internal static string CustomBoard {
            get {
                return ResourceManager.GetString("CustomBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check in..
        /// </summary>
        internal static string FailedToCheckIn {
            get {
                return ResourceManager.GetString("FailedToCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fake location detected!.
        /// </summary>
        internal static string FakeLocationDetected {
            get {
                return ResourceManager.GetString("FakeLocationDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Country.
        /// </summary>
        internal static string FilterByCountry {
            get {
                return ResourceManager.GetString("FilterByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter pin.
        /// </summary>
        internal static string FilterPin {
            get {
                return ResourceManager.GetString("FilterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Location.
        /// </summary>
        internal static string GetLocation {
            get {
                return ResourceManager.GetString("GetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m here!.
        /// </summary>
        internal static string GetLocationHere {
            get {
                return ResourceManager.GetString("GetLocationHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide date and month.
        /// </summary>
        internal static string HideDateAndMonth {
            get {
                return ResourceManager.GetString("HideDateAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use this app.
        /// </summary>
        internal static string HowTo {
            get {
                return ResourceManager.GetString("HowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Got to ”Settings” and set your Country of Residence..
        /// </summary>
        internal static string Instruciton1 {
            get {
                return ResourceManager.GetString("Instruciton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Go to &quot;Location&quot; and Get Locatoin.
        /// </summary>
        internal static string Instruciton2 {
            get {
                return ResourceManager.GetString("Instruciton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Go to &quot;Banner&quot; and pull to refresh..
        /// </summary>
        internal static string Instruciton3 {
            get {
                return ResourceManager.GetString("Instruciton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon Voyage!.
        /// </summary>
        internal static string Instruciton4 {
            get {
                return ResourceManager.GetString("Instruciton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Key..
        /// </summary>
        internal static string InvalidAPIKey {
            get {
                return ResourceManager.GetString("InvalidAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file selected.
        /// </summary>
        internal static string InvalidFileSelected {
            get {
                return ResourceManager.GetString("InvalidFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or corrupted file.
        /// </summary>
        internal static string InvalidOrCorruptedFile {
            get {
                return ResourceManager.GetString("InvalidOrCorruptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the following your current location?.
        /// </summary>
        internal static string IsTheFollowingYourLocatoin {
            get {
                return ResourceManager.GetString("IsTheFollowingYourLocatoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load offerings.
        /// </summary>
        internal static string LoadOfferings {
            get {
                return ResourceManager.GetString("LoadOfferings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly for.
        /// </summary>
        internal static string MonthlySubFor {
            get {
                return ResourceManager.GetString("MonthlySubFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Country.
        /// </summary>
        internal static string NewCountry {
            get {
                return ResourceManager.GetString("NewCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Region.
        /// </summary>
        internal static string NewRegion {
            get {
                return ResourceManager.GetString("NewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No duplicate countries.
        /// </summary>
        internal static string NoDuplicateCountries {
            get {
                return ResourceManager.GetString("NoDuplicateCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation overwrites the existing file..
        /// </summary>
        internal static string OverwriteExistingFile {
            get {
                return ResourceManager.GetString("OverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For getting more locations, subscribe or configure your own Google Maps API key in Settings..
        /// </summary>
        internal static string PayWallDescription {
            get {
                return ResourceManager.GetString("PayWallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first 3 months are free for new subscribers..
        /// </summary>
        internal static string PayWallSubTitle {
            get {
                return ResourceManager.GetString("PayWallSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect flags worldwide!.
        /// </summary>
        internal static string PayWallTitle {
            get {
                return ResourceManager.GetString("PayWallTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again..
        /// </summary>
        internal static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please relaunch the app to enable the data..
        /// </summary>
        internal static string RelaunchToEnable {
            get {
                return ResourceManager.GetString("RelaunchToEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore backup.
        /// </summary>
        internal static string RestoreBackup {
            get {
                return ResourceManager.GetString("RestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have used this app on a previous device, please make sure to restore the backup before using it again..
        /// </summary>
        internal static string RestoreBeforeUse {
            get {
                return ResourceManager.GetString("RestoreBeforeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is set successfully!.
        /// </summary>
        internal static string SetAPIKey {
            get {
                return ResourceManager.GetString("SetAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify your key if you&apos;d like to..
        /// </summary>
        internal static string SpecifyAPI {
            get {
                return ResourceManager.GetString("SpecifyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriptions:.
        /// </summary>
        internal static string Subscription {
            get {
                return ResourceManager.GetString("Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go near the selected pin and tap &apos;Check In&apos; below..
        /// </summary>
        internal static string TapCheckInNearTheSelectedPin {
            get {
                return ResourceManager.GetString("TapCheckInNearTheSelectedPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location..
        /// </summary>
        internal static string UnableToGetLocation {
            get {
                return ResourceManager.GetString("UnableToGetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get location data..
        /// </summary>
        internal static string UnableToGetLocationData {
            get {
                return ResourceManager.GetString("UnableToGetLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexplored Location.
        /// </summary>
        internal static string UnexploredLocation {
            get {
                return ResourceManager.GetString("UnexploredLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly for.
        /// </summary>
        internal static string YearlySubFor {
            get {
                return ResourceManager.GetString("YearlySubFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not near the location..
        /// </summary>
        internal static string YouAreNotNearTheLocation {
            get {
                return ResourceManager.GetString("YouAreNotNearTheLocation", resourceCulture);
            }
        }
    }
}
